spring.application.name=crud

# Configuração da URL de conexão (JDBC)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_POSTGRES}

# Credenciais de acesso
spring.datasource.username=${USER_POSTGRES}
spring.datasource.password=${PASSWORD_POSTGRES}

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# update: Cria as tabelas se não existirem e atualiza a estrutura se houver mudanças
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console (ótimo para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate use o dialeto correto para o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect